version: '3'
services:
  dockergc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./docker-gc-exclude:/etc/docker-gc-exclude
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRON="0 7 * * *"
      - FORCE_IMAGE_REMOVAL=1
      - FORCE_CONTAINER_REMOVAL=1
      - GRACE_PERIOD_SECONDS=3600
      - DRY_RUN=0
      - CLEAN_UP_VOLUMES=1
      - TZ=Pacific/Auckland
