version: '3'

services:
  app:
    image: cthulhoo/ttrss-fpm-pgsql-static
    restart: unless-stopped
    environment:
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_NAME=ttrss
      - TTRSS_DB_PASS=${TTRSS_DB_PASS}
      - TTRSS_DB_HOST=192.168.1.107
      - TTRSS_SELF_URL_PATH=https://tt-rss.latchee.com/tt-rss
    volumes:
      - app:/var/www/html
      - tt-rss:/opt/tt-rss
    networks:
      - ttrssbridge

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static
    restart: unless-stopped
    environment:
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_NAME=ttrss
      - TTRSS_DB_PASS=${TTRSS_DB_PASS}
      - TTRSS_DB_HOST=192.168.1.107
    volumes:
      - app:/var/www/html
      - tt-rss:/opt/tt-rss:ro
    networks:
      - ttrssbridge
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh

  web-nginx:
    image: cthulhoo/ttrss-web-nginx
    restart: unless-stopped
    ports:
      - 8280:80
    volumes:
      - app:/var/www/html:ro
    networks:
      - ttrssbridge
    depends_on:
      - app

volumes:
  app:
  tt-rss:

networks:
  ttrssbridge:
    driver: bridge
