version: "3.7"
services:

 vaultwarden:
  image: "vaultwarden/server:latest"
  container_name: "vaultwarden"
  hostname: "vaultwarden"
  restart: always
  volumes:
   - "vaultwarden_vol:/data/"
  environment:
   - "DATABASE_URL=mysql://vaultwarden:${VW_DB_PWD}@192.168.1.105/vaultwarden"
   - "ADMIN_TOKEN=${VW_ADMIN_TK}"
   - "RUST_BACKTRACE=1"
  ports:
   - "8082:80"

volumes:
 vaultwarden_vol:
