version: '3.8'
services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 30 12 * * *"
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_NOTIFICATION_URL: smtp://mail.latchee.com:25/?fromaddress=watchtower@latchee.com&toaddresses=mail@latchee.com
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: "2"
      WATCHTOWER_NOTIFICATION_TITLE_TAG: Watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
